Bounties-Network/Explorer

.gitignore, package.json
@somethiiing Good news!!! JUST RUN:
`yarn storyboard-deploy`
The rest is history :D
=> Storyboard deploys now functional

src/components/BountyCard/BountyCard.module.scss, src/components/BountyCard/index.js, src/components/Circle/Circle.module.scss, src/components/Payout/Payout.module.scss, src/components/Payout/index.js, src/components/Text/Text.module.scss, src/components/Text/index.js, src/containers/ExplorerPage/ExplorerPage.module.scss, src/styles/variables.scss, yarn.lock
- Refine bounty card styles and styles of components within bounty card:
circle, payout, text, and variables.
=> Refactor bounty card component

config/webpack.config.prod.js
=> Production webpack for deploys

src/public-modules/Client/sagas.js, src/public-modules/index.js
=> Fixed delay import, and syntax issue.

src/components/Dropdown/index.js, src/components/NotificationDropdown/index.js
=> Bugfix notification elements

src/components/Button/Button.module.scss, src/components/Button/index.js, src/stories/Button.stories.js
=> Button loading

package.json, src/components/Header/index.js, src/components/NotificationDropdown/index.js, src/fontAwesome.js, src/layout/App/index.js, yarn.lock
=> Library format to handle font awesome icons.

package.json, src/components/Button/Button.module.scss, src/components/Button/index.js, src/components/Circle/Circle.module.scss, src/components/Circle/index.js, src/components/Cropper/Cropper.module.scss, src/components/Cropper/index.js, src/components/FileUpload/FileUpload.module.scss, src/components/FileUpload/index.js, src/components/Loader/Loader.module.scss, src/components/Loader/index.js, src/fontAwesome.js, src/stories/Circle.stories.js, src/stories/Croppie.stories.js, src/stories/FileUpload.stories.js, src/stories/Loader.stories.js, src/utils/helpers.js, yarn.lock
=> Uploads and image cropping

src/components/Cropper/index.js, src/stories/Button.stories.js, src/styles/Croppie.scss
@corwinharrell I added the vendor stylesheet here :).
=> Cropper vendor styles

package.json, src/components/NumberInput/NumberInput.module.scss, src/components/NumberInput/index.js, src/components/Social/Social.module.scss, src/components/Social/index.js, src/components/ZeroState/ZeroState.module.scss, src/components/ZeroState/index.js, src/fontAwesome.js, src/stories/NumberInput.stories.js, src/stories/Social.stories.js, src/stories/ZeroState.stories.js, yarn.lock
Number input, zero state, and social components done :)
=> Number input zero states social

src/components/Pill/Pill.module.scss, src/components/Pill/index.js, src/stories/Pill.stories.js
@corwinharrell updates - used the strategy of a span as a child... which would have a classname vs. styles - but did that just for demo purposes on storybook.  Also fixed the flex issue, and cleaned up a few things (added textcolor prop)
=> Pill and stories updated to take textColor.

src/components/Modal/Modal.module.scss, src/components/Modal/index.js, src/components/ZeroState/ZeroState.module.scss, src/components/ZeroState/index.js, src/containers/CreateBounty/CreateBounty.module.scss, src/containers/CreateBounty/index.js, src/containers/Login/LoginLock.js, src/containers/Login/components/AddressMismatch.js, src/containers/Login/components/ErrorModal.js, src/containers/Login/components/SignIn.js, src/containers/Login/components/SigningIn.js, src/containers/Login/components/UnlockWallet.js, src/containers/Login/components/WalletRequired.js, src/hocs/RequireLoginComponent.js, src/hocs/RequireLoginComponent.module.scss, src/layout/App/index.js, src/layout/Header/index.js, src/public-modules/Authentication/index.js, src/public-modules/Bounties/sagas.js, src/styles/index.scss
=> Feature loginlocked pages

src/containers/CreateBounty/index.js, src/explorer-components/PageCard/PageCard.module.scss, src/explorer-components/PageCard/index.js
=> Component pagecard

package.json, src/components/MarkdownEditor/MarkdownEditor.module.scss, src/components/MarkdownEditor/index.js, src/components/Modal/Modal.module.scss, src/components/Modal/index.js, src/components/Text/index.js, src/components/Textbox/Textbox.module.scss, src/components/Textbox/index.js, src/fontAwesome.js, src/stories/MarkdownEditor.stories.js, src/utils/constants.js, yarn.lock
=> Markdown editor created. Modals managed when content is too large.

src/layout/App/index.js
=> Fixed double loading.

src/public-modules/Authentication/sagas.js
=> Fix incorrect user endpoint

src/components/Modal/index.js, src/components/Toast/index.js, src/components/ToastContainer/index.js, src/containers/CreateBounty/index.js, src/containers/CreateBounty/sagas.js, src/containers/Login/components/WalletRequired.js, src/explorer-components/TransactionWalkthrough/TransactionWalkthrough.js, src/explorer-components/TransactionWalkthrough/TransactionWalkthrough.module.scss, src/explorer-components/TransactionWalkthrough/index.js, src/hocs/TransactionWalkthrough.js, src/index.js, src/layout/App/index.js, src/layout/Header/index.js, src/public-modules/Bounty/sagas.js, src/public-modules/Transaction/index.js, src/public-modules/Transaction/sagas.js, src/public-modules/Transaction/selectors.js, src/public-modules/index.js
=> Transactions

src/explorer-components/TransactionWalkthrough/index.js, src/hocs/TransactionWalkthrough.js, src/public-modules/Authentication/sagas.js
@c-o-l-o-r last piece of transactions. Gonna merge for now as I'm gonna deploy.
=> Success modal with transactions is finished.

src/components/FileUpload/index.js, src/containers/CreateBounty/CreateBounty.module.scss, src/containers/CreateBounty/CreateBountyForm.js, src/containers/CreateBounty/constants.js, src/containers/CreateBounty/index.js, src/hocs/TransactionWalkthrough.js, src/layout/App/index.js, src/public-modules/Bounty/constants.js, src/public-modules/Bounty/index.js, src/public-modules/Bounty/sagas.js, src/public-modules/Bounty/selectors.js, src/public-modules/FileUpload/index.js, src/public-modules/FileUpload/sagas.js, src/public-modules/FileUpload/selectors.js, src/public-modules/index.js
=> Clean up create bounty

src/containers/Settings/UserSettings.js, src/public-modules/Settings/sagas.js, src/public-modules/Skills/sagas.js, src/public-modules/index.js
=> Adding transaction flow to settings

src/containers/CreateBounty/CreateBountyForm.js
=> Restrict letters and reasonable steps.

src/components/Modal/Modal.module.scss, src/containers/Login/components/AddProfileDetails.js, src/containers/Login/components/baseStyles.module.scss, src/containers/Login/reducer.js, src/containers/Login/sagas.js, src/containers/Profile/ProfileDetails.js, src/containers/Settings/UserSettings.js, src/containers/Settings/constants.js, src/utils/helpers.js
=> Fix settings issues

src/components/Modal/Modal.module.scss, src/containers/Bounty/ActionBar.js, src/containers/Bounty/components/ModalManager.js, src/containers/Bounty/components/index.js, src/containers/Bounty/components/listItems/SubmissionItem.js, src/containers/Bounty/components/modals/ContributeFormModal.js, src/containers/Bounty/components/modals/FulfillBountyFormModal.js, src/containers/Bounty/components/modals/IncreasePayoutFormModal.js, src/containers/Bounty/components/modals/TransferOwnershipFormModal.js, src/containers/Bounty/index.js, src/containers/CreateBounty/CreateBountyForm.js, src/containers/CreateBounty/index.js, src/containers/Dashboard/components/BountiesPanel/index.js, src/containers/Dashboard/components/BountyItem/index.js, src/containers/Dashboard/components/UserStats/index.js, src/containers/Explorer/ExplorerBody.js, src/containers/Profile/ProfileBounties.js, src/containers/Profile/index.js, src/containers/Profile/reducer.js, src/explorer-components/BountyCard/BountyCard.module.scss, src/explorer-components/BountyCard/index.js, src/explorer-components/TransactionWalkthrough/index.js, src/hocs/TransactionWalkthrough.js, src/layout/App/index.js, src/layout/Header/index.js, src/public-modules/Bounty/index.js, src/public-modules/Bounty/sagas.js, src/utils/validators.js
Lots of bug fixes across the site. Also finishing up the bounty page.
=> Bounty page continued

src/components/Modal/index.js, src/containers/Bounty/ActionBar.js, src/containers/Bounty/ActionBar.module.scss, src/containers/Bounty/Bounty.module.scss, src/containers/Bounty/SubmissionsAndCommentsCard.js, src/containers/Bounty/index.js, src/containers/Login/FunctionalLoginLock.js, src/containers/Login/reducer.js, src/hocs/FunctionalLoginLock.js, src/layout/App/index.js, src/public-modules/Client/sagas.js, src/public-modules/Transaction/index.js, src/public-modules/Transaction/sagas.js
=> Login protector hoc

src/components/MarkdownEditor/MarkdownEditor.module.scss, src/components/MarkdownEditor/index.js, src/components/Modal/Modal.module.scss, src/components/Modal/index.js, src/components/Textbox/Textbox.module.scss, src/containers/CreateBounty/CreateBounty.module.scss, src/containers/CreateBounty/CreateBountyForm.js, src/containers/CreateBounty/index.js, src/containers/Login/components/UnlockWallet.js, src/explorer-components/FormSection/FormSection.module.scss, src/explorer-components/FormSection/index.js
=> Create bounty page responsive styles

src/public-modules/Review/sagas.js, src/public-modules/Reviews/sagas.js, src/public-modules/Transaction/sagas.js, src/public-modules/UserInfo/sagas.js, src/public-modules/config.json
=> Added platform to transaction post

package.json, src/containers/Bounty/SubmissionsAndCommentsCard.js, src/containers/Bounty/components/ModalManager.js, src/containers/Bounty/components/NewCommentForm.js, src/containers/Bounty/components/listItems/CommentItem.js, src/containers/Bounty/components/listItems/SubmissionItem.js, src/containers/Bounty/components/modals/IssueRatingFormModal/index.js, src/containers/Bounty/components/modals/IssueRatingFormModal/reducer.js, src/containers/Bounty/components/modals/IssueRatingFormModal/sagas.js, src/containers/Bounty/components/modals/IssueRatingFormModal/selectors.js, src/containers/Bounty/index.js, src/containers/Bounty/reducer.js, src/containers/Bounty/sagas.js, src/containers/Bounty/selectors.js, src/public-modules/Fulfillment/index.js, src/public-modules/Fulfillment/sagas.js, src/public-modules/Fulfillment/selectors.js, src/public-modules/Review/selectors.js, src/public-modules/Settings/index.js, src/reducers.js, src/sagas.js, yarn.lock
Reverts Bounties-Network/Explorer#89
=> Revert "Rating modal continued"

src/containers/Settings/constants.js, src/utils/constants.js
Update the post request to post to the right key for comments saved.
=> Comment received function functional

src/components/ZeroState/index.js, src/containers/Bounty/ActionBar.js, src/containers/Bounty/SubmissionsAndCommentsCard.js, src/containers/Bounty/components/modals/IncreasePayoutFormModal.js, src/containers/Bounty/components/modals/KillBountyFormModal.js, src/containers/Dashboard/components/ActivityPanel/index.js, src/containers/Dashboard/components/BountiesPanel/index.js, src/containers/Dashboard/components/SubmissionsPanel/index.js, src/containers/Explorer/ExplorerBody.js, src/containers/Leaderboard/LeaderboardCard.js, src/containers/Login/components/AddProfileDetails.js, src/containers/Login/components/SigningIn.js, src/containers/NotificationDropdown/index.js, src/containers/Profile/ProfileBounties.js, src/containers/Profile/index.js, src/explorer-components/TransactionWalkthrough/index.js, src/fontAwesome.js, src/utils/constants.js
updates icons, copy, small UI quirks
=> Copy updates

src/components/ToastContainer/ToastContainer.module.scss, src/containers/NotificationDropdown/index.js, src/public-modules/Notification/sagas.js, src/utils/constants.js
=> Misc fixes

src/layout/Header/index.js
I kept clicking this and being disappointed it didn't work!
=> Add link to upper left bee icon

src/public-modules/Notification/selectors.js
Quick fix - notification sort by created.
=> Fix notification sorting bug.

src/components/DatePicker/index.js, src/components/Dropdown/index.js, src/containers/Bounty/components/ModalManager.js, src/containers/Bounty/components/modals/ActivateDeadFormModal.js, src/containers/Bounty/components/modals/ActivateDraftFormModal.js, src/containers/Bounty/components/modals/ContributeFormModal.js, src/containers/Bounty/components/modals/ExtendDeadlineFormModal.js, src/containers/Bounty/components/modals/IncreasePayoutFormModal.js, src/containers/Bounty/index.js, src/containers/CreateBounty/CreateBountyForm.js, src/containers/CreateBounty/index.js, src/layout/Header/index.js, src/public-modules/Bounty/sagas.js, src/public-modules/Fulfillments/sagas.js, src/utils/helpers.js
This fixes a number of things:
1. Timezones are now managed correctly across the app. This makes it so deadline bugs are all fixed now.
2. Token symbols and token amounts are prefilled on forms like (Activate, contribute, etc.)
Other bugfixes.
=> More and more fixes

src/components/Button/Button.module.scss, src/components/Circle/Circle.module.scss, src/components/FullAddressBar/FullAddressBar.module.scss, src/components/Modal/Modal.module.scss, src/containers/Profile/FilterNav.js, src/containers/Profile/FilterNav.module.scss, src/containers/Profile/Profile.module.scss, src/containers/Profile/ProfileBounties.js, src/containers/Profile/ProfileBounties.module.scss, src/containers/Profile/ProfileDetails.js, src/containers/Profile/ProfileDetails.module.scss, src/containers/Profile/components/About/About.module.scss, src/containers/Profile/components/About/index.js, src/containers/Profile/components/Elsewhere/Elsewhere.module.scss, src/containers/Profile/components/Elsewhere/index.js, src/containers/Profile/components/NetworkStats/NetworkStats.module.scss, src/containers/Profile/components/NetworkStats/index.js, src/containers/Profile/components/ProfileAvatar/ProfileAvatar.module.scss, src/containers/Profile/components/ProfileAvatar/index.js, src/containers/Profile/components/Skills/Skills.module.scss, src/containers/Profile/components/Skills/index.js, src/containers/Profile/index.js, src/explorer-components/TransactionWalkthrough/index.js
- Restructure of profile bounties section to more closely resemble and function like explorer
- Responsive design for profile
=> Responsive Design for User Profile

src/components/Network/index.js, src/components/SideOverlay/SideOverlay.module.scss, src/components/SideOverlay/index.js, src/components/Sidebar/Sidebar.module.scss, src/components/Sidebar/index.js, src/containers/Bounty/index.js, src/containers/Explorer/Explorer.module.scss, src/containers/Explorer/ExplorerBody.js, src/containers/Explorer/ExplorerBody.module.scss, src/containers/Explorer/FilterNav.module.scss, src/containers/Explorer/index.js, src/fontAwesome.js, src/layout/App/App.module.scss, src/layout/App/constants.js, src/layout/App/index.js, src/layout/App/reducer.js, src/layout/App/selectors.js, src/layout/Header/Header.module.scss, src/layout/Header/index.js, src/reducers.js
@c-o-l-o-r @codeluggage 
This introduces our new mobile navigation :).
Enjoy :D
=> Mobile sidenav

src/containers/Explorer/FilterNav.module.scss
=> Fixed height and width bugs.

src/containers/Explorer/index.js, src/public-modules/Bounties/index.js
@c-o-l-o-r Back and Forward will now also reload the data/filters properly.
=> Back and forward now reload and work with query params.

src/containers/Explorer/index.js
=> Added stage filter toggle ref.

src/components/SideOverlay/SideOverlay.module.scss
=> Opacity is properly 1.

src/containers/Profile/components/Elsewhere/index.js, src/containers/Settings/UserSettings.js, src/containers/Settings/sagas.js, src/public-modules/Client/sagas.js, src/public-modules/Settings/sagas.js, src/public-modules/config.json, src/utils/validators.js
@villanuevawill @codeluggage I updated the settings sagas to send the payload to the api server instead of the eth profiles contract. I also added a toast after a successful (or failed) request to updated the profile.
=> Feature off chain user profiles

src/public-modules/config.json, src/utils/constants.js
This refers to the new ID's added in the backend PR here: https://github.com/Bounties-Network/BountiesAPI/pull/124
=> Add draft notifications for new draft events in the backend

src/components/DatePicker/index.js, src/components/TextInput/index.js, src/containers/Bounty/components/modals/ExtendDeadlineFormModal.js, src/containers/CreateBounty/CreateBountyForm.js, src/utils/helpers.js, src/utils/validators.js
:) Native phone datepicker and validation if cell phone.
=> Native phone datepicker and validation if cell phone.

src/explorer-components/TransactionWalkthrough/index.js
=> Fix typo in transaction dialog

src/containers/Bounty/SubmissionsAndCommentsCard.js, src/containers/Bounty/SubmissionsAndCommentsCard.module.scss, src/containers/Bounty/index.js, src/public-modules/Comments/index.js, src/public-modules/Comments/sagas.js
@villanuevawill @codeluggage this PR goes with https://github.com/Bounties-Network/BountiesAPI/pull/131
basically just changing up the sagas to accept the new schema and finished implementing the load more comment functionality
=> Implement load more functionality for comments and integrate new endpoint schema

src/containers/Profile/index.js, src/explorer-components/BountyCard/index.js, src/layout/App/index.js
=> Remove platform and sort to filter nav on profile page

package.json, src/components/Modal/Modal.module.scss, src/components/Modal/index.js, src/components/SideOverlay/SideOverlay.module.scss, src/components/SideOverlay/index.js, src/components/Text/index.js, src/containers/Bounty/components/ModalManager.js, src/containers/Bounty/components/modals/ActivateDeadFormModal.js, src/containers/Bounty/components/modals/ActivateDraftFormModal.js, src/containers/Bounty/components/modals/ContributeFormModal.js, src/containers/Bounty/components/modals/ExtendDeadlineErrorModal.js, src/containers/Bounty/components/modals/ExtendDeadlineFormModal.js, src/containers/Bounty/components/modals/FulfillBountyFormModal.js, src/containers/Bounty/components/modals/IncreasePayoutFormModal.js, src/containers/Bounty/components/modals/IssueRatingFormModal/index.js, src/containers/Bounty/components/modals/KillBountyFormModal.js, src/containers/Bounty/components/modals/TransferOwnershipFormModal.js, src/containers/Login/FunctionalLoginLock.js, src/containers/Login/LoginLock.js, src/containers/Login/index.js, src/explorer-components/TransactionWalkthrough/index.js, yarn.lock
=> Modal animations - ready to rock :)

src/components/Dropdown/index.js, src/components/Modal/Modal.module.scss, src/components/Modal/index.js, src/components/Network/Network.module.scss, src/components/Network/index.js, src/containers/Bounty/components/modals/ActivateDeadFormModal.js, src/containers/Bounty/components/modals/ActivateDraftFormModal.js, src/containers/Bounty/components/modals/ContributeFormModal.js, src/containers/Bounty/components/modals/ExtendDeadlineFormModal.js, src/containers/Bounty/components/modals/FulfillBountyFormModal.js, src/containers/Bounty/components/modals/IncreasePayoutFormModal.js, src/containers/Bounty/components/modals/IssueRatingFormModal/index.js, src/containers/Bounty/components/modals/TransferOwnershipFormModal.js, src/containers/CreateBounty/index.js, src/containers/Login/FunctionalLoginLock.js, src/containers/Login/LoginLock.js, src/containers/Login/components/WrongNetwork.js, src/containers/Login/components/index.js, src/fontAwesome.js, src/hocs/FunctionalLoginLock.js, src/hocs/ModalFormReset.js, src/layout/Header/index.js, src/public-modules/Client/sagas.js, src/public-modules/config.json, src/styles/index.scss, src/utils/constants.js, src/utils/validators.js
This fixers a bunch. Please read commit messages for clarity.
A couple more left in the next PR coming soon:
=> Lots of fixups

src/components/SideOverlay/SideOverlay.module.scss, src/components/SideOverlay/index.js
@villanuevawill @codeluggage "fixed" header issue and *fixed* flicker issue with side overlay on iOS🎉
=> Fix iOS side overlay

src/components/Dropdown/Dropdown.module.scss, src/components/Dropdown/index.js, src/components/Modal/Modal.module.scss, src/components/Modal/index.js, src/containers/Bounty/ActionBar.js, src/containers/Login/LoginLock.js, src/containers/Login/components/AddressMismatch.js, src/containers/Login/components/UnlockWallet.js, src/containers/Login/components/WalletRequired.js, src/containers/Login/components/WrongNetwork.js, src/containers/Profile/index.js, src/layout/App/index.js, src/public-modules/Client/index.js, src/public-modules/Client/sagas.js, src/public-modules/Notification/index.js, src/styles/slick.scss
@c-o-l-o-r @codeluggage  :) Read the commits - lots and lots of random fixes.
=> Another round of fixes

src/components/SideOverlay/index.js, src/containers/Bounty/components/NewCommentForm.js, src/containers/CreateBounty/CreateBountyForm.js, src/containers/Explorer/Explorer.module.scss, src/containers/Explorer/index.js, src/containers/NotificationDropdown/index.js, src/containers/Profile/Profile.module.scss, src/containers/Profile/constants.js, src/containers/Profile/index.js, src/layout/App/App.module.scss, src/layout/App/index.js, src/layout/App/reducer.js, src/styles/index.scss
=> Filter nav arrangement rewritten.

src/components/Cropper/index.js, src/components/Textbox/Textbox.module.scss, src/containers/BountiesPanel/BountiesPanel.module.scss, src/containers/BountiesPanel/index.js, src/containers/Bounty/index.js
@villanuevawill @codeluggage made a few small fixes:
1. set the default active tab on the bounty page to be comments
2. added view all link on bounties panel
3. fixed the orientation issue when uploading iOS images
4. fixed text box bug on create bounty page
=> Few small fixes

src/containers/Bounty/SubmissionsAndCommentsCard.js, src/containers/Bounty/index.js, src/containers/ExplorerBody/index.js, src/containers/Profile/index.js, src/explorer-components/BountyCard/index.js, src/public-modules/Bounty/sagas.js
@villanuevawill @codeluggage the tab on the bounty page can now be opened to either submissions or comments via a query parameter
=> Load bounty tab by query

src/containers/FilterNav/index.js
=> fixed platform field in filter nav to use config settings

src/components/Currency/Currency.module.scss, src/components/Currency/index.js, src/containers/Bounty/index.js, src/containers/ExplorerBody/index.js, src/containers/Leaderboard/LeaderboardCard.js, src/containers/Leaderboard/components/LeaderItem.js, src/explorer-components/BountyCard/BountyCard.module.scss, src/explorer-components/BountyCard/index.js, src/explorer-components/BountyItem/index.js, src/explorer-components/Currency/index.js, src/explorer-components/SubmissionItem/index.js, src/hocs/CurrencyModifier.js, src/stories/Currency.stories.js, src/utils/helpers.js
@villanuevawill @codeluggage added currency display component and a wrapped version of it to manage whether to show USD on top of token on top (depending on if there is a default token or not).
=> Feature value component

src/components/Currency/Currency.module.scss, src/components/Currency/index.js, src/containers/Bounty/index.js, src/containers/Leaderboard/components/LeaderItem.js, src/explorer-components/BountyCard/BountyCard.module.scss, src/explorer-components/BountyCard/index.js, src/explorer-components/BountyItem/index.js, src/explorer-components/SubmissionItem/index.js
@villanuevawill @codeluggage added some styling to the primary token symbol text
=> add styling to currency symbol

src/containers/Bounty/SubmissionsAndCommentsCard.js, src/public-modules/Bounty/sagas.js
@villanuevawill @codeluggage there was a copy issue where the `Your submissions are only visible to you and the bounty issuer.` showed up even though I was the issuer. Also, I realized that there was an error where the draft that was saved had an incorrect privacy setting.
=> Fix remove copy for bounty owner

src/containers/Profile/ProfileDetails.js
=> Fix template issue

src/components/Table/index.js, src/containers/Bounty/ActionBar.module.scss, src/containers/Bounty/SubmissionsAndCommentsCard.js, src/containers/Bounty/SubmissionsAndCommentsCard.module.scss, src/containers/Bounty/components/NewCommentForm.js, src/containers/Bounty/components/listItems/CommentItem.module.scss, src/containers/Bounty/components/listItems/SubmissionItem.module.scss, src/containers/Leaderboard/components/LeaderItem.module.scss, src/containers/Profile/components/Elsewhere/index.js, src/explorer-components/SubmissionItem/SubmissionItem.module.scss, src/explorer-components/SubmissionItem/index.js, src/fontAwesome.js, src/styles/index.scss
Fixes for various visual bugs noticed after initial launch
=> Visual bug fixes

src/containers/Bounty/SubmissionsAndCommentsCard.js
Reverts Bounties-Network/Explorer#171
=> Revert "Add zero state when owner is logged in and there are 0 submissions"

src/components/Currency/Currency.module.scss, src/components/Currency/index.js, src/containers/Bounty/Bounty.module.scss, src/containers/Bounty/index.js, src/explorer-components/BountyItem/BountyItem.module.scss
@villanuevawill @codeluggage @corwinharrell fixed a padding issue on the currency component and made the component go inline on mobile on the bounty page.
=> Fix currency padding

src/components/Currency/Currency.module.scss, src/components/Currency/index.js, src/containers/Bounty/Bounty.module.scss, src/containers/Bounty/index.js, src/explorer-components/BountyItem/BountyItem.module.scss
Reverts Bounties-Network/Explorer#170
=> Revert "Fix currency padding"

src/components/Avatar/index.js, src/containers/Bounty/components/listItems/SubmissionItem.js, src/containers/Bounty/components/modals/IssueRatingFormModal/index.js, src/containers/Bounty/index.js, src/containers/Explorer/index.js, src/containers/Profile/components/Elsewhere/index.js, src/containers/Profile/index.js, src/utils/helpers.js
@villanuevawill @codeluggage i'm created shortener functions for long file names and urls. @corwinharrell may want to weigh in here (and possibly play around with lengths) that are ideal.
=> shorten url & file names that are very long

src/containers/Bounty/SubmissionsAndCommentsCard.js, src/public-modules/Fulfillments/constants.js
@villanuevawill @codeluggage submissions are now loaded 10 at a time.
=> add load more button to submissions on bounty page

src/containers/Profile/ProfileDetails.js, src/containers/Profile/components/About/index.js
=> Show user languages even if no organization was provided

src/containers/Bounty/ActionBar.js
@villanuevawill @codeluggage okay this one is pretty simple. @corwinharrell let us know if you want to make the fulfillment button have a specific look for Gitcoin bounties.
=> Fulfill Gitcoin bounties on Gitcoin

src/components/Social/index.js
@villanuevawill @codeluggage @mbeylin 
Trello: https://trello.com/c/Dcpdl7OZ/17-25-55-the-links-to-share-a-bounty-on-fb-and-twitter-are-inverted
=> Fix incorrect social media icons on bounty page

src/components/Loader/index.js, src/layout/App/index.js
@villanuevawill @codeluggage changed the main loader to blue.
Trello: https://trello.com/c/Q1x5R5tM/95-20-45-change-the-colour-of-the-spinner-for-the-pages-to-be-blue
=> Change default page loader to blue

src/containers/Login/components/AddProfileDetails.js, src/containers/Settings/UserSettings.js, src/form-components/index.js, src/public-modules/Settings/sagas.js
Trello: https://trello.com/c/exXRchyB
Adds `email_interest` for the user settings. Corresponds to BountiesAPI PR: https://github.com/Bounties-Network/BountiesAPI/pull/193
=> Email interest signup

src/containers/Bounty/SubmissionsAndCommentsCard.js, src/containers/Bounty/index.js, src/containers/Bounty/reducer.js, src/containers/Bounty/sagas.js
Trello: https://trello.com/c/uj1eVE6P
We want to show the most relevant tab, meaning either public submissions, your own submission, or comments.
=> Always show the most interesting tab on the bounty page

src/containers/Settings/UserSettings.js, src/public-modules/Settings/sagas.js
@villanuevawill fixed the variable name on the frontend to match https://github.com/Bounties-Network/BountiesAPI/pull/203
=> change email marketing variable name for clarity

package.json, src/containers/Bounty/components/modals/ActivateDeadFormModal.js, src/containers/Bounty/components/modals/ActivateDraftFormModal.js, src/containers/Bounty/components/modals/ContributeFormModal.js, src/containers/Bounty/components/modals/ExtendDeadlineFormModal.js, src/containers/Bounty/components/modals/FulfillBountyFormModal.js, src/containers/Bounty/components/modals/IncreasePayoutFormModal.js, src/containers/Bounty/components/modals/IssueRatingFormModal/index.js, src/containers/Bounty/components/modals/TransferOwnershipFormModal.js, src/containers/CreateBounty/CreateBountyForm.js, src/containers/Login/components/ErrorModal.js, src/containers/Settings/UserSettings.js, src/hocs/FormInput.js, src/layout/App/App.module.scss, src/utils/asyncValidators.js, src/utils/helpers.js, yarn.lock
@villanuevawill @codeluggage okay we had to upgrade to redux-forms 7.4.2 to take advantage of performing async validation during onChange events on fields. This introduced some new complexity like debouncing the change event. I had to promisify this in order for redux-form to understand it.
=> Better token validation

src/containers/Leaderboard/LeaderboardCard.js, src/containers/Leaderboard/LeaderboardCard.module.scss
@villanuevawill @codeluggage this PR will address the issues the dropdown when it was in a zero state.
=> Fix leaderboard dropdown issues

src/public-modules/berlin_settings.json, src/public-modules/hiring_settings.json, src/public-modules/sf_settings.json
=> SF settings file added for new auto deploys

src/containers/Bounty/components/modals/ActivateDeadFormModal.js, src/containers/Bounty/components/modals/ActivateDraftFormModal.js, src/layout/Header/index.js
@villanuevawill @codeluggage hey here is the fix for the max depth issue we're having on the activate draft form. Not sure why this was an issue though because it was working on all the other modals.
Trello: https://trello.com/c/RKLdnFLt/173-activate-draft-button-is-failing-and-just-showing-a-white-page
=> Fix redux-form render issue max depth issue

src/containers/Leaderboard/LeaderboardCard.js
- temporarily commenting out until we think through the feature in more depth. For now we are still defaulting to bounties network on the leaderboard.
=> Remove platform dropdown

src/layout/Header/index.js
Just a quick clean up after https://github.com/Bounties-Network/Explorer/pull/198 that was meant to be in that PR, now that the lock isn't being used in this file
=> Remove wallet lock code that is no longer used

src/components/Dropdown/Dropdown.module.scss, src/components/Dropdown/index.js, src/components/Sidebar/Sidebar.module.scss, src/containers/Leaderboard/LeaderboardCard.js, src/layout/App/App.module.scss, src/layout/App/index.js
=> Animation, proper hover effects andmore.

src/components/Modal/Modal.module.scss, src/explorer-components/PageCard/PageCard.module.scss, src/explorer-components/SubmissionItem/SubmissionItem.module.scss
Bug fixes for:
https://trello.com/c/pmQURGFS/144-title-stretches-screen-out-on-mobile
https://trello.com/c/x4nOyOau/134-z-index-bug-on-mobile
https://trello.com/c/Na4DVRGM/141-extra-spacing-on-submissions-table
=> UI bug fixes - 10/1

src/containers/CreateBounty/CreateBountyForm.js, src/public-modules/Client/sagas.js, src/utils/asyncValidators.js
@villanuevawill looks like that fix suggested (https://github.com/erikras/redux-form/issues/3944) worked to solve the issues with the validation. I also could not reproduce the issue you described after the fix. I added a comment with the Github issue of the bug.
=> Fix async validation issue

src/containers/Profile/index.js
Reverts Bounties-Network/Explorer#228
For update on the switch.
=> Revert "Rating modal link"

src/components/Cropper/index.js, src/containers/Bounty/SubmissionsAndCommentsCard.js, src/containers/Bounty/components/listItems/SubmissionItem.js, src/containers/Bounty/index.js, src/containers/Bounty/sagas.js, src/containers/ExplorerBody/index.js, src/containers/Leaderboard/LeaderboardCard.js, src/containers/Login/LoginLock.js, src/containers/NotificationDropdown/index.js, src/containers/Profile/ProfileDetails.js, src/containers/Profile/components/ReviewsModal/index.js, src/containers/Settings/UserSettings.js, src/containers/Settings/constants.js, src/containers/Settings/reducer.js, src/containers/Settings/sagas.js, src/containers/Settings/selectors.js, src/containers/SubmissionsPanel/index.js, src/containers/UserStats/index.js, src/hocs/FunctionalLoginLock.js, src/layout/Header/index.js, src/public-modules/FileUpload/sagas.js, src/public-modules/Settings/index.js, src/public-modules/Settings/sagas.js, src/public-modules/Settings/selectors.js, src/public-modules/staging_settings.json, src/reducers.js, src/utils/request.js
@villanuevawill @codeluggage this is the frontend portion of removing our dependence on IPFS for uploading profile images. I still have a little work on the API, but I think this part is pretty close to done. I'd like to get it all on staging ASAP so I can do more testing.
=> Save profile images directly to s3

src/containers/Bounty/components/listItems/SubmissionItem.js, src/containers/Bounty/components/listItems/SubmissionItem.module.scss, src/utils/helpers.js
@villanuevawill @codeluggage this is small PR to display images associated with submissions
=> Show images in submission card for fulfillments

src/containers/Leaderboard/LeaderboardCard.js
=> fix missing leaderboard image

src/containers/Bounty/index.js, src/containers/Settings/EmailPreferences.js, src/containers/Settings/constants.js, src/fontAwesome.js, src/public-modules/Settings/sagas.js, src/utils/constants.js
Trello: https://trello.com/c/95BzIwv7
BountiesAPI PR: https://github.com/Bounties-Network/BountiesAPI/pull/214
This adds the notification COMPLETED_BOUNTY to email settings and notifications. Took an early stab at the copy for this, feedback welcomed!
=> Add notification for bounty running out of funds

src/containers/Profile/index.js
@villanuevawill 
Continues the work in https://github.com/Bounties-Network/Explorer/pull/217 with simplifications and improvements. No longer needs to wait for the reviews to load and avoids visual switch from one tab to the other.
=> Most interesting review tab improved

src/components/Dropdown/Dropdown.module.scss, src/components/Dropdown/index.js, src/containers/Bounty/components/SEOHeader.js, src/layout/App/App.module.scss, src/layout/App/index.js
https://trello.com/c/QZQAvHjC/151-20-45-add-a-trailing-ellipsis-to-the-meta-tags-for-descriptions
https://trello.com/c/6RJYkgnO/180-bug-tos-tooltip-blocks-buttons-on-filternav-even-when-not-visible
- Animation right on TOS subnav
- Tooltip TOS does not block filternav
- Ellipses for metatag descriptions
=> Bugfixes :)

src/containers/Bounty/components/ModalManager.js, src/containers/Bounty/components/modals/IssueRatingFormModal/index.js, src/containers/Leaderboard/LeaderboardCard.js, src/explorer-components/FilterNav/index.js, src/public-modules/Bounties/selectors.js, src/public-modules/Fulfillment/index.js, src/public-modules/Fulfillment/sagas.js, src/public-modules/Leaderboard/index.js, src/public-modules/Leaderboard/selectors.js, src/public-modules/Review/index.js, src/public-modules/Review/sagas.js, src/public-modules/config.js, src/public-modules/production_settings.json, src/public-modules/staging_settings.json, src/utils/helpers.js
@villanuevawill @codeluggage here is the PR to implement subplatforms
=> Feature sub platforms

src/public-modules/Fulfillment/sagas.js
@villanuevawill @codeluggage I accidentally set the posting schema to the posting platform in the last PR. This will fix it.
=> Fix posting schema

src/public-modules/Fulfillment/sagas.js
Reverts Bounties-Network/Explorer#245
=> Revert "Fix posting schema"

package.json, src/public-modules/production_settings.json
- Adds Prague to explorer
- Adds Prague to deploy-all
=> Add Prague to explorer

src/explorer-components/FulfillmentStagePill/index.js
@villanuevawill @codeluggage removes the rejected label from not accepted submission on bounties that have been completed or are dead.
=> Remove rejected label

src/components/MarkdownEditor/index.js, src/containers/Bounty/components/listItems/SubmissionItem.js, src/containers/Bounty/index.js, src/utils/helpers.js
@villanuevawill @codeluggage for some reason I didn't realize showdown was used again on the bounty page. I added my extension for opening links in new tabs there as well.
=> add showdown extension to bounty page

src/public-modules/Bounties/selectors.js, src/public-modules/Leaderboard/selectors.js, src/utils/global.js, src/utils/helpers.js
- Config reliant function moved to global
=> Config should not be referenced via component library

src/components/Sidebar/Sidebar.module.scss, src/layout/Header/Header.module.scss
Trello: https://trello.com/c/Cl8KYapC
@corwinharrell @villanuevawill Is this a silly way to fix this? I saw that the z-index of 15 was set for a reason in a PR 6 days ago, so figured setting the sidebar z-index above that made the most sense.
=> Increase z-index above the 15 z-index used for the modal

src/components/Sidebar/Sidebar.module.scss
Fixes odd scroll issues on the sidevar navtext for windows
=> No scroll issues on windows/linux for the sidenav

src/containers/CreateBounty/CreateBounty.module.scss, src/containers/CreateBounty/CreateBountyForm.js
@villanuevawill @codeluggage not a great solution, but I believe this is the best thing I could come up with w/o fixing redux-form itself. I opened an issue on their repo about this: https://github.com/erikras/redux-form/issues/4235
=> Fix create bounty form bug

src/components/SideOverlay/SideOverlay.module.scss
Fixes issue where side filter hides behind the header
=> Filtersidenave is no longer behind the header.

src/containers/Profile/components/ReviewsModal/ReviewItem.js
-Review list now uses linked avatar (react router vs. hard a tag)
=> Linked avatar included to use react router vs. hard link

src/containers/CreateBounty/CreateBountyForm.js
=> Hide draft validation on balance

src/public-modules/bees_settings.json, src/public-modules/berlin_settings.json, src/public-modules/hiring_settings.json, src/public-modules/prague_settings.json, src/public-modules/production_settings.json, src/public-modules/sf_settings.json
api.bounties.network and rinkeby.bounties.network vs new.api and newrinkeby
=> Pointing to api and rinkeby vs the new

src/containers/Bounty/components/listItems/SubmissionItem.js, src/containers/Bounty/components/listItems/SubmissionItem.module.scss
@villanuevawill @codeluggage this fixes the issue where the accept button was falling to the bottom of the submission card when on mobile.
=> Fix styling of accept button on mobile

src/containers/Profile/components/About/index.js
@villanuevawill @codeluggage fixed a spelling error on the profile page
=> Fix spelling of organization

src/public-modules/Reviews/sagas.js
@villanuevawill @codeluggage order reviews from newest to oldest
=> Order reviews from newest to oldest

src/components/Checkbox/index.js
=> Marketing email checkbox now functional.

src/layout/App/reducer.js, src/layout/App/sagas.js, src/layout/App/selectors.js
=> Add global saga to send new page view request only when pathname changes

src/containers/Login/components/WalletRequired.js
=> Update to toshi wallet link for ios

src/components/Tabs/index.js
Forgot to put this in the last PR
=> Fix bug when tab count is 0

README.md
=> Link to our new documentation hub

src/containers/Bounty/ActionBar.js
Reverts Bounties-Network/Explorer#278
=> Revert "Hide deactivate button if bounty is in a completed state"

src/components/FileUpload/index.js, src/containers/Bounty/components/modals/ActivateDeadFormModal.js, src/containers/Bounty/components/modals/ActivateDraftFormModal.js, src/containers/Bounty/components/modals/ContributeFormModal.js, src/containers/Bounty/components/modals/IncreasePayoutFormModal.js, src/containers/CreateBounty/CreateBountyForm.js
Reverts Bounties-Network/Explorer#282
=> Revert "Deactivate Token Vaidation"

src/containers/Profile/index.js
=> reset on profile is broken ... it shows all bounties after clicking

src/components/PageBanner/PageBanner.module.scss, src/components/PageBanner/index.js, src/components/ProgressBar/ProgressBar.module.scss, src/components/ProgressBar/index.js, src/containers/Dashboard/Dashboard.module.scss, src/containers/Dashboard/index.js, src/containers/Profile/selectors.js, src/stories/PageBanner.stories.js, src/stories/ProgressBar.stories.js
Updating a couple small things from #258 before merging. Cheers
=> Feature profile progress

src/utils/request.js
Reverts Bounties-Network/Explorer#313
=> Revert "Stop 401s recording as API errors"

src/utils/request.js
This should actually fix it instead of throwing error.
=> Actually fix rollbar 401

src/containers/Dashboard/index.js, src/public-modules/Settings/index.js, src/public-modules/Settings/sagas.js
- Added new sagas and actions to call dismissed banner endpoint.
=> user-dismissed-banner-track

src/utils/request.js
Getting too many notifications for 404s.
=> Issue warning for 404 instead of error

src/utils/request.js
I realized I wanted to see why we're getting so many 404 errors :-)
=> Better error logging for requests

src/containers/Bounty/Bounty.module.scss
fixed some padding and margins
=> added flex grow to account for smaller descriptions.

src/stories/Cropper.stories.js
I was originally planning to fix a bug with the cropper allowing for uploads while in a disabled state, but I wasn't able to reproduce.
=> Updated cropper story

.gitignore, package.json, src/public-modules/Bounties/index.js
The offset was not being reset when a new batch of bounties was loaded.
=> Fixed issue where load more button would disappear after changing sort

src/public-modules/Transaction/sagas.js
=> Dismiss old toasts when more than 3 attempt to appear

src/public-modules/Authentication/sagas.js
=> Don't redirect user to Explorer on logout

src/utils/constants.js
I added the new accepted/rejected notifications to the explorer.
=> Add new notification constants

src/containers/Settings/EmailPreferences.js, src/containers/Settings/constants.js, src/public-modules/Settings/sagas.js
This adds toggles on the settings page to update you email preferences.
=> Add application state changes to settings page

src/containers/Bounty/ActionBar.js
=> Hide actionbar when user is logged out but wallet matches

src/public-modules/production_settings.json
=> Add paris bounties to the main explorer

src/containers/Bounty/components/ModalManager.js, src/containers/Bounty/components/modals/ActivateDeadFormModal.js, src/containers/Bounty/components/modals/ActivateDraftFormModal.js, src/containers/Bounty/components/modals/ContributeFormModal.js, src/containers/Bounty/components/modals/IncreasePayoutFormModal.js, src/utils/validators.js
This avoids a user from inputting more decimals than a token contract supports.
=> Check token decimals in bounty modals

package.json, src/containers/Dashboard/Dashboard.module.scss
=> Remove scrollbar from dashboard cards

src/containers/Bounty/ActionBar.js
=> Fix link to gitcoin bounties

src/public-modules/Utilities/Web3Client.js
=> updated infura endpoint to v3

src/utils/validators.js
=> fixed increase payout modal

src/components/Textbox/index.js, src/containers/Login/components/WalletRequired.js
Finally squashed the bug with fulfillment descriptions having a jumping cursor when editing
=> Cleaning bugs

package.json, src/components/Button/Button.module.scss, src/components/Checkbox/Checkbox.module.scss, src/components/Pill/Pill.module.scss, src/components/Sidebar/Sidebar.module.scss, src/components/Switch/Switch.module.scss, src/containers/BountiesPanel/index.js, src/containers/Bounty/components/cards/SubmissionsCard.js, src/containers/Bounty/components/listItems/SubmissionItem.js, src/containers/Bounty/components/listItems/SubmissionItem.module.scss, src/containers/Leaderboard/components/LeaderItem.module.scss, src/fontAwesome.js, src/index.js, src/layout/App/constants.js, src/stories/Sidebar.stories.js, src/styles/flexboxgrid.css, src/styles/index.scss, src/styles/variables.scss, src/theme.js, yarn.lock
* Add styled system to be used in the future as a foundation for refactoring our components to used Styled-System + Styled Components (CSS in JS)
* Add base `theme.js` file for styled system
* Reformat color palette code
* Clean up design for submissions
* Fix font flicker bug for switch component
=> Add Styled System + Small Design Improvements

src/containers/Bounty/components/listItems/SubmissionItem.js, src/containers/CreateBounty/CreateBountyForm.js, src/public-modules/Fulfillments/index.js, src/styles/index.scss
=> Fix issues with multi-line list items

src/containers/CreateBounty/CreateBountyForm.js, src/containers/CreateBounty/index.js
=> Sm00g15 master

src/containers/CreateBounty/CreateBountyForm.js, src/containers/CreateBounty/index.js
This could also be done by adding an || in the if statement just below the added one if you'd like too.
=> Debug broken form validation on the Bounties Explorer

src/components/Avatar/index.tsx, src/components/Text/Text.module.scss, src/containers/Bounty/Bounty.module.scss, src/containers/Bounty/components/listItems/CommentItem.module.scss, src/containers/Bounty/components/modals/ContributeFormModal.js, src/containers/Bounty/components/modals/FulfillerApplicationFormModal.js, src/containers/Bounty/components/modals/Modals.module.scss, src/containers/Bounty/components/modals/TransferOwnershipFormModal.js, src/containers/Dashboard/Dashboard.module.scss, src/containers/Login/components/AddressMismatch.js, src/containers/Login/components/baseStyles.module.scss
Reverts Bounties-Network/Explorer#402
=> Revert "Ui bugs fixes 1/9/19"

src/components/Avatar/index.tsx, src/components/Text/Text.module.scss, src/containers/Bounty/Bounty.module.scss, src/containers/Bounty/components/listItems/CommentItem.module.scss, src/containers/Bounty/components/modals/ContributeFormModal.js, src/containers/Bounty/components/modals/FulfillerApplicationFormModal.js, src/containers/Bounty/components/modals/Modals.module.scss, src/containers/Bounty/components/modals/TransferOwnershipFormModal.js, src/containers/Dashboard/Dashboard.module.scss, src/containers/Login/components/AddressMismatch.js, src/containers/Login/components/baseStyles.module.scss
Reverts Bounties-Network/Explorer#403
=> Revert "Revert "Ui bugs fixes 1/9/19""

src/components/ListGroup/ListGroup.module.scss, src/containers/Bounty/components/cards/Cards.module.scss, src/containers/Bounty/components/cards/CommentsCard.js, src/containers/Bounty/components/listItems/CommentItem.js, src/containers/Bounty/components/listItems/CommentItem.module.scss, src/containers/Bounty/components/modals/FulfillBountyFormModal.js, src/containers/Bounty/components/modals/FulfillerApplicationFormModal.js, src/styles/DatePicker.scss
Fixes for the following:
- https://www.notion.so/openfora/Comments-div-should-hide-overflowing-text-or-deal-with-it-better-when-they-include-long-links-on--eee9c166d477408f8fb99835bfa834ec
- https://www.notion.so/openfora/Create-bounty-date-selection-UI-bugs-out-110354de1fb749f3affb19ba0e502c8d
=> UI bug fixes 10/19
