- src/containers/Dashboard/components/ActivityPanel/index.js
- src/public-modules/Notification/helpers.js
ref: https://github.com/Bounties-Network/BountiesAPI/pull/119
Will merge these together once we are ready for a resync.
This is compatible with the new updates on the notification client that saves the true event date. This lets us give the correct date on notifications after a sync.
> Compatible with new event dates

- src/containers/ActivityPanel/index.js
- src/containers/BountiesPanel/index.js
- src/containers/Dashboard/index.js
- src/containers/SubmissionsPanel/index.js
@villanuevawill @codeluggage this should fix the issues we were having with really slow load times. They were being caused by tons of extraneous requests to the API which were caused mainly by the mobile containers being hidden only by CSS. This means that they were mounted in parallel with the desktop containers and there sagas were running in tandem. It still isn't perfect, but I wanted to push this up as an immediate fix and then talk about better patterns for the sagas because I'm not happy with the "pattern" I have laid out thus far.
> Fix slow loading times

- src/containers/Bounty/components/modals/FulfillBountyFormModal.js
@villanuevawill @codeluggage there is a strange issue such that the fulfillments form was not getting submitted due to the `buttonType === button`. I'm still not sure how this happened, if either of you have any ideas on what might be the underlining cause I would love to find out.
> Fix issue where fulfillment modal was not submitting

- src/containers/Bounty/index.js
- src/public-modules/Bounty/sagas.js
@villanuevawill @codeluggage if bounty page is set to load comments as the active tab, ensure that fulfillments is loaded in the background
> Fix submissions count error

- src/utils/constants.js
Now that more users than just the issuer receive a notification when a comment has been posted on a bounty they're involved with, we want that to reflect in the copy.
> Copy change to make comment notification user agnostic

- src/containers/Bounty/SubmissionsAndCommentsCard.js
@villanuevawill @codeluggage I added an additional view to the submissions card on the bounty page. It seemed weird to use the same copy for the bounty owner when there are no submissions as a random user who is viewing the bounty. It has been updated to explain that there are currently 0 submissions but that they would appear there as they were submitted. It also remind the user that the bounty's submissions are private so only the fulfiller and themselves will be able to view the submissions.
> Add zero state when owner is logged in and there are 0 submissions

- src/containers/Bounty/components/listItems/SubmissionItem.module.scss
@villanuevawill @codeluggage fixed an issue with newlines not rendering in submission descriptions
> set white-space to prewrap on submission descriptions

- src/containers/Bounty/index.js
@villanuevawill @codeluggage @corwinharrell while merging and rebase this somehow got lost, but I added back in the specific color for tokens on the bounty page when it is a token specific explorer.
> fix incorrect currency color on bounty page

- src/components/Modal/index.js
- src/containers/Profile/ProfileDetails.js
- src/containers/Profile/components/About/index.js
@villanuevawill @codeluggage for some reason when a modal has a string in the description, but it is inject a variable into the jsx it shows up in the children as an object instead of a string.
> Fix text styles of several modals

- src/containers/Leaderboard/LeaderboardCard.js
@villanuevawill here is that hotfix to hide the dropdown on the berlin explorer
> add logic to hide dropdown if there is only one platform

- src/layout/App/index.js
- src/utils/global.js
- src/utils/request.js
- Fixes bug where the mobile nave does not close on selecting the privacy or TOS link.
- Fixes issues introduced from the storybook deploy
> Mobile nav closes on tos/privacy check

- src/components/Avatar/index.js
Trello: https://trello.com/c/8SNCzND2
This makes the Avatar component fall back to address link if no src prop is available.
> Fix rating modal profile links

- src/public-modules/Bounties/selectors.js
- src/public-modules/production_settings.json
- src/public-modules/staging_settings.json
- src/utils/helpers.js
@villanuevawill @codeluggage this PR adds a new field in the config.json that allows us to describe "subplatforms". For example, `sf` and `berlin` could be subplatforms of `bounties-network`.
> Add utility function to expand platforms into their subplatforms

- src/containers/Profile/index.js
- src/containers/Profile/reducer.js
- src/containers/Profile/sagas.js
Trello: https://trello.com/c/z8oOHfn9
This branches off of https://github.com/Bounties-Network/Explorer/pull/209, which should be merged first. This branch can target master after that. For now, it targets https://github.com/Bounties-Network/Explorer/pull/209 in order to show the correct diff.
A few considerations worth discussing: 
- Only one type of reviews will be loaded at a time. I check if there are any reviews (issuer) and if there are none, I switch to the fulfiller reviews. This does not guarantee that there are fulfiller reviews, but it is efficient and simple. 
- A querystring can override this "most interesting tab", and that's why this PR is based off of https://github.com/Bounties-Network/Explorer/pull/209
- State for having set the tab already was used because reviews go …
> Always show the most interesting review tab

- src/containers/Profile/ProfileDetails.js
- src/containers/Profile/index.js
- src/containers/Profile/reducer.js
- src/containers/Profile/sagas.js
@c-o-l-o-r @villanuevawill 
Currently deployed to https://staging.bounties.network
Try this profile to see it in action: https://staging.bounties.network/profile/0xf4b6774fca6c692ad278959a8aec795a65c8fd9b/
Previous work on this would either have issues with the order of loading, or with visual switching of the network stats after the page had loaded. 
This was because the stats are not fully loaded by the time the page renders, and to avoid a re-render and showing the network stats switching, the logic needed to be moved inside the ProfileDetails.
This ended up being much more complex that we wanted, because the network stats switch can be set with both query string and its own logic based on the fulfiller and issuer stats.
A refactor of the concept of toggling might make this even …
> Network stats switch loading fix

- src/components/DatePicker/index.js
References https://trello.com/c/1oUw7Xzo/193-bug-datepicker-component-does-not-apply-mindate-to-the-mintime-parameter
Min time automatically gets set to match the time on the min date
> Datepicker applies minTime for minDate property

- src/components/MarkdownEditor/index.js
- src/components/Text/index.js
- src/containers/Bounty/components/listItems/SubmissionItem.js
- src/containers/Bounty/index.js
- src/containers/Profile/components/Elsewhere/index.js
@villanuevawill @codeluggage this PR addresses the recent bug in the text's link functionality and this Trello card https://trello.com/c/pIdnjmTX/175-bug-any-links-on-the-bounty-page-to-outside-links-or-to-associated-files-should-always-open-in-a-new-tab-using-targetblank.
> Implement absolute links in explorer

- src/components/Button/index.js
- src/components/FileUpload/index.js
@villanuevawill @codeluggage this fixes the issue on the fulfillment modal in firefox where the upload file button would actually submit the form. I used a span tag just like I did for the cropper component.
> Make upload file button a span tag to avoid firebox bug

- src/containers/Bounty/components/listItems/SubmissionItem.js
@villanuevawill @codeluggage I realized that ipfs links on the fulfillment cards weren't opening in new tab. This PR fixes that for consistency.
> Force file upload links on fulfillments to open in new tab

- package.json
- src/components/Textbox/index.js
- src/containers/Bounty/components/NewCommentForm.js
- src/containers/Bounty/components/NewCommentForm.module.scss
- src/containers/Bounty/components/listItems/CommentItem.module.scss
- yarn.lock
This follows up on https://github.com/Bounties-Network/Explorer/pull/239
Trello: https://trello.com/c/GdwgjN6X
Up on staging: https://staging.bounties.network (though I only saw it properly take effect in a new private Firefox window, not after hard refreshing a regular window)
- Adds the https://github.com/andreypopp/react-textarea-autosize textarea
- Styles it to fit our `$base-input-height` and not be resizeable, for our comment input
> Growing textarea

- package.json
@villanuevawill 
Simply add a deploy command that skips staging, so we can keep in-development builds there without overwriting when we want to deploy to all production environments.
> Add another deploy choice that avoids staging: deploy-all-production

- src/components/Modal/index.js
Modal logic is fairly complex dealing with animations. This makes sure that if a modal is unmounting and it is the last VISIBLE modal, the modal-open class will be removed properly from the page body.
> Modal lock issue resolved.

- config/polyfills.js
- package.json
- src/explorer-components/BountyCard/index.js
- src/layout/App/index.js
- src/utils/helpers.js
- yarn.lock
Edge and older versions of IE use scrollTop = 0 vs the function call on scrollTo()
This fixes the issues where we broke on those browsers.
> Fixed edge/ie issue that was breaking javascript

- src/public-modules/production_settings.json
@c-o-l-o-r  this removes berlin. We originally talked about only having valued bounties ont he main explorer. Berlin coin had no value.
> Remove berlin

- src/containers/Login/LoginLock.js
- src/containers/Login/components/UnlockWallet.js
- src/containers/Login/index.js
- src/hocs/FunctionalLoginLock.js
- src/public-modules/Client/sagas.js
We originally had modals set up for this, but it became more complex.
@corwinharrell there is no way to know if a person's wallet is locked or if they have not given approval.
In this case, any time the (Your wallet is locked) dialogue shows, I just automate showing the metamask approval request. If they reject, the wallet is locked modal stays.
The other alternative... would be to show the metamask request modal any time a transaciton request or login request comes up. If they accept it (or they have preivously accepted), then the first modal shows. If not, then no modals show. However, metamask can be slow at times and it may seem choppy. Additionally, we can't have consistency with the locked pages (dashboard or settings), whereas the other solution keeps everything consistent.
> Manages new EIP-1102 privacy web3 injection rules

- src/utils/asyncValidators.js
@villanuevawill @codeluggage the async validator was doing a <= when it should have just been a <.
> Fix async validator

- src/utils/validators.js
- Go from 4 to 7 characters for the email validation regex
> Quickfix: Expand email validation to match .network addresses

- src/public-modules/Client/sagas.js
Fixes, `Error: Possible EventEmitter memory leak detected. 101 data listeners added. Use emitter.setMaxListeners() to increase limit` caused by rebinding the web3 instance repeatedly to metamask which attaches 10 event listeners to. (this adds 10 per second until it is overloaded)
> This fixes the event emitter leak issue.

- src/public-modules/Drafts/sagas.js
@villanuevawill fixed the issue where all drafts would load for a single user.
> Use session address to load drafts instead of wallet address

- src/components/FileUpload/index.js
not sure where that extra `: null` came from
> fix typo in file upload

- src/containers/Settings/EmailPreferences.js
`hasOwnProperty` was returning `true` even for `undefined`.
> Default unknown email preferences to false

- src/index.js
When setting values with many decimal places, `BigNumber.js` would return an exponential number which would confused web3. I reconfigured `BigNumber.js` to always return non-exponential numbers.
> Fix issue contributing / creating bounties with very small denominations

- src/containers/Login/components/AddProfileDetails.js
There were two instances of modals inside this file and I missed updating the second one:
> Add profile icon to second profile details modal

- src/containers/Bounty/components/modals/IssueRatingFormModal/IssueRatingFormModal.module.scss
- src/containers/Bounty/components/modals/IssueRatingFormModal/index.js
- Remove bounty preview card in order to simplify the ratings modal as users felt they were hindered by the amount of content in this modal instance and important information was hidden below the "fold" on small screens
> Simplify ratings modal
